### PR TITLE
US B32G22-230_Contacts

### PR DESCRIPTION
**Pull request by Sco0per**
US03 : Contacts Functionality 
@MayaIshanova , please review and approve

### CODE REVIEW

**Review by MayaIshanova — COMMENTED** [review]
Nice work.

**Comment by MayaIshanova** [comment]
Good

**Comment by Sco0per** [comment]
Hi maya , please approve my PR before close it

**Review by MayaIshanova — COMMENTED** [review]
Good work

**Review by MayaIshanova — COMMENTED** [review]
Reviewed

**Review by MayaIshanova — APPROVED** [review]
Reviewed

**Review by MayaIshanova — COMMENTED** [review]
nice

**Pull request merged**
