### PR TITLE
Add DeletedPages Function

### PR DESCRIPTION
**Pull request by NailBul**

### CODE REVIEW

**Review by Cetinkaplan — APPROVED** [review]
Looks perfect to me  nail..

**Comment by Cetinkaplan** [comment]
good job

**Review by MayaIshanova — APPROVED** [review]
nice work

**Review by MayaIshanova — APPROVED** [review]
Because I'm working on a File page too can you add some of your codes to a BasePage?

**Review by MayaIshanova — APPROVED** [review]
nice

**Review by MayaIshanova — APPROVED** [review]
;)

**Review by MayaIshanova — APPROVED** [review]
good

**Comment by MayaIshanova** [comment]
GJ

**Review by MayaIshanova — COMMENTED** [review]
good

**Pull request closed without merging**
